architecture-beta
    group lang(cloud)[Programming Languages]
    group fe(cloud)[Frontend]
    group be(cloud)[Backend]
    group db(cloud)[Databases]
    group cloud(cloud)[Cloud and DevOps]
    group tools(cloud)[Tooling]

    service java(logos:java)[Java] in lang
    service python(logos:python)[Python] in lang
    service c(logos:c)[C] in lang
    service cpp(logos:c-plusplus)[Cpp] in lang
    service js(logos:javascript)[JavaScript] in lang
    service ts(logos:typescript-icon)[TypeScript] in lang
    service bash(logos:bash-icon)[Bash] in lang

    service react(logos:react)[React] in fe
    service next(logos:nextjs-icon)[NextJS] in fe
    service tailwind(logos:tailwindcss-icon)[Tailwind] in fe
    service bootstrap(logos:bootstrap)[Bootstrap] in fe

    service spring(logos:spring-icon)[Spring] in be
    service node(logos:nodejs-icon)[NodeJS] in be
    service express(logos:express)[Express] in be
    service django(logos:django-icon)[Django] in be

    service prisma(logos:prisma)[Prisma] in db
    service postgres(logos:postgresql)[Postgres] in db
    service mongo(logos:mongodb-icon)[MongoDB] in db
    service firebase(logos:firebase)[Firebase] in db
    service supabase(logos:supabase-icon)[Supabase] in db

    service aws(logos:aws)[AWS] in cloud
    service gcp(logos:google-cloud)[GCP] in cloud
    service docker(logos:docker-icon)[Docker] in cloud
    service k8s(logos:kubernetes)[Kubernetes] in cloud
    service ansible(logos:ansible)[Ansible] in cloud
    service ghactions(logos:github-actions)[GHActions] in cloud

    service gitlab(logos:gitlab)[GitLab] in tools
    service linux(logos:linux-tux)[Linux] in tools
    service vscode(logos:visual-studio-code)[VSCode] in tools
    service postman(logos:postman-icon)[Postman] in tools

    lang:B -- T:fe
    fe:B -- T:be
    be:B -- T:db
    db:B -- T:cloud
    cloud:B -- T:tools
